name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - id: last-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
    outputs:
      release_id: ${{ steps.last-release.outputs.id }}

  build-release:
    strategy:
      matrix:
        board:
          - avaota-a1
        distro:
          - jammy: [cli, gnome, xfce]
          - noble: [cli]
          - bullseye: [cli]
          - bookworm: [cli]
    uses: AvaotaSBC/AvaotaOS/.github/workflows/Build-AvaotaOS.yaml@main
    needs: [prepare_release]
    with:
      config-board: ${{ matrix.board }}
      config-distro: ${{ matrix.distro }} 
      config-distro-type: ${{ matrix.distro-type }} 
      config-release_id: ${{ needs.prepare_release.outputs.release_id }}
  
