name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - id: last-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
    outputs:
      release_id: ${{ steps.last-release.outputs.id }}
      release_ver: ${{ steps.last-release.outputs.release }}

  build-kernel:
    strategy:
      matrix:
        board:
          - avaota-a1
    uses: AvaotaSBC/AvaotaOS/.github/workflows/Build-AvaotaOS-Kernel.yaml@main
    needs: [prepare_release]
    with:
      config-board: ${{ matrix.board }}
      config-release_id: ${{ needs.prepare_release.outputs.release_id }}
      config-release_ver: ${{ needs.prepare_release.outputs.release_ver }}

  build-release:
    strategy:
      matrix:
        board:
          - avaota-a1
        distro:
          - jammy
          - noble
        distro-type:
          - cli
          - gnome
          - xfce
        exclude:
          - distro: noble
            distro-type: gnome
          - distro: noble
            distro-type: xfce
    uses: AvaotaSBC/AvaotaOS/.github/workflows/Build-AvaotaOS.yaml@main
    needs: [prepare_release, build-kernel]
    with:
      config-board: ${{ matrix.board }}
      config-distro: ${{ matrix.distro }} 
      config-distro-type: ${{ matrix.distro-type }} 
      config-release_id: ${{ needs.prepare_release.outputs.release_id }}
  
