name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - id: last-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
    outputs:
      release_id: ${{ steps.last-release.outputs.id }}

  build-avaota-release:
    strategy:
      matrix:
        board: [avaota-a1]
        distro: [jammy, noble, bullseye, bookworm, trixie]
        include:
          - distro-type: cli
          - distro-type: gnome
    uses: AvaotaSBC/AvaotaOS/.github/workflows/Build-AvaotaOS.yaml@main
    needs: [prepare_release]
    with:
      config-board: ${{ matrix.board }}
      config-distro: ${{ matrix.distro }} 
      config-distro-type: ${{ matrix.distro-type }} 
      config-release_id: ${{ needs.prepare_release.outputs.release_id }}
  
